name: Pre-commit

on: [issues, pull_request]

jobs:
  test-tools:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [2.7]

    steps:
    - uses: actions/checkout@v1
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Test (no working dir)
      run: |
      pwd && env
      
    - name: Test (working dir)
      working-directory: $GITHUB_WORKSPACE/virtualization-sdk/virtualization-sdk/tools
      run: |
      pwd && env
        
    - name: Build local dependencies
      working-directory: $GITHUB_WORKSPACE/virtualization-sdk/virtualization-sdk/tools
      run: |
        ./gradlew 
        
    - name: Install dependencies
      working-directory: $GITHUB_WORKSPACE/virtualization-sdk/virtualization-sdk/tools
      run: |
        python -m pip install --upgrade pip
        pip install -r lock.requirements.txt -r lock.dev-requirements.txt
        
    - name: Test with pytest
      working-directory: $GITHUB_WORKSPACE/virtualization-sdk/virtualization-sdk/tools
      run: |
        pip install pytest
        PYTHONPATH=src/main/python pytest src/test/python/
