name: Pre-commit

on: [pull_request]

jobs:
  test-tools:
    name: Test the dvp-tools package

    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        python-version: [2.7]
        os: [ubuntu-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      working-directory: tools
      run: |
        python -m pip install --upgrade pip
        pip install -r lock.requirements.txt -r lock.dev-requirements.txt
        
    - name: Test with pytest
      working-directory: tools
      run: |
        pip install pytest
        PYTHONPATH=src/main/python pytest src/test/python/
        
  lint:
    name: Lint ${{ matrix.package }}

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        package: [tools]
        
    steps:
      - uses: actions/checkout@v1
    
      - name: Set up Python 2.7
        uses: actions/setup-python@v1
        with:
          python-version: 2.7
   
      - name: Install flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8
        
      - name: Run flake8 on src directory
        working-directory: ${{ matrix.package }}
        run: python -m flake8 src/main/python
    
      - name: Run flake8 on test directory
        working-directory: ${{ matrix.package }}
        run: python -m flake8 test/main/python
      
  format:
    name: Check format ${{ matrix.package}}
    
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        package: [tools]
      
    steps:
      - uses: actions/checkout@v1
      
      - name: Check src format
        uses: lgeiger/black-action@v1.0.1
        with:
          args: "${{ matrix.package }}/src/main/python -t py27 --check"
     
      - name: Check test format
        uses: lgeiger/black-action@v1.0.1
        with:
          args: "${{ matrix.package }}/src/test/python -t py27 --check"
