name: Release

on:
  push:
    branches:
      - refs/tags/*
    
jobs:
  test:
    name: Testing this action
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        package: [tools]
    
    steps:
      - uses: actions/checkout@v1
      
      - name: Set up Python 2.7
        uses: actions/setup-python@v1
        with:
          python-version: 2.7
