name: Release

on: [issues]
    
jobs:

  docs:
    name: Publish docs
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
      - uses: dschep/install-pipenv-action@v1
      - name: Publish docs
        working-directory: docs/
        run: pipenv --python 3.7 run mkdocs gh-deploy
