name: Release

on: [issues]
    
jobs:

  docs:
    name: Publish docs
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
            python-version: '3.7'
      - name: Install mkdocs
        run: pip install mkdocs mkdocs-material markdown-include mkdocs-awesome-pages-plugin
      - name: Build docs
        working-directory: docs/
        run: mkdocs build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2.4.0
        env:
            ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
            PUBLISH_BRANCH: gh-pages
            PUBLISH_DIR: docs/site
