name: Release

on: [issues]
    
jobs:

  docs:
    name: Publish docs
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
            python-version: '3.7'
      - name: Install pipenv
        run: pip3 install --upgrade pip pipenv
      - name: Setup environment
        working-directory: docs/
        run: pipenv install
      - name: Publish docs
        working-directory: docs/
        run: pipenv run mkdocs gh-deploy
