name: Release

on:
  push:
    tags:
    - v[0-9]\.[0-9]\.[0-9].*
    
jobs:
  test:
    name: Testing this action
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
      - name: Echo
        run: echo "Made it here"
