name: Release

on:
  push:
    branches:
      - refs/tags/*
    
jobs:
  test:
    name: Testing this action
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
      - name: Echo
        run: echo "Made it here"
