name: Release

on: [issues]
    
jobs:
  test:
    name: Testing this action
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        package: [tools]
    
    steps:
      - uses: actions/checkout@v1
      
      - name: Set up Python 2.7
        uses: actions/setup-python@v1
        with:
          python-version: 2.7
      
      - name: Install twine and wheel
        run: pip install twine wheel
      
      - name: Build Python package
        working-directory: ${{ matrix.package }}
        run: python setup.py sdist bdist_wheel
      
      - name: Publish distribution to Test PyPI
        working-directory: ${{ matrix.package }}
        run: |
          twine upload --repository-url https://test.pypi.org/legacy/ -u __token__ -p ${{ secrets.pypi_password }} dist/*.tar.gz
          twine upload --repository-url https://test.pypi.org/legacy/ -u __token__ -p ${{ secrets.pypi_password }} dist/*.whl
